[package]
name = "slight-runtime-configs"
version = "0.1.0"
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lib]
doctest = false

[dependencies]
wit-bindgen-wasmtime = { workspace = true }
anyhow = { workspace = true }
wit-error-rs = { workspace = true }
slight-common = { path = "../common" }
rand = "0.8"
spiderlightning = { path = "../.." }
toml = "0.5"
short-crypt = "1"
azure-app-configuration = { git = "https://github.com/danbugs/azure-app-configuration.git", rev = "e6cc5bdd3d5dedb6fb48f0dcdf0ec674c8033cf6" }
tracing = { workspace = true }
async-trait = { workspace = true }
regex = "1.6"

[dev-dependencies]
tempdir = "0.3"
