[package]
name = "slight-runtime-configs"
version = "0.1.0"
edition = "2021"
authors = ["DeisLabs Engineering Team"]

[lib]
doctest = false

[dependencies]
wit-bindgen-wasmtime = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "a79a4be33d76ddf62839ba71602c26a96610ef7c" }
anyhow = "1.0"
wit-error-rs = { git = "https://github.com/danbugs/wit-error-rs", rev = "05362f1a4a3a9dc6a1de39195e06d2d5d6491a5e" }
slight-runtime = { path = "../runtime" }
argon2rs = "0.2.5"
rand = "0.8.5"
crossbeam-channel = "0.5.5"
uuid = "1"
spiderlightning = { path = "../.." }
slight-events-api = { path = "../events-api" }
toml = "0.5.9"
short-crypt = "1"

[dev-dependencies]
tempdir = "0.3"
