[package]
name = "slight-runtime"
version = "0.1.0"
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }
wasi-common = { workspace = true }
wasi-cap-std-sync = { workspace = true }
anyhow = { workspace = true }
as-any = "0.3"
wit-bindgen-wasmtime = { workspace = true }
crossbeam-channel = "0.5"
slight-events-api = { path = "../events-api" }
slight-http-api = { path = "../http-api/" }
tracing = { version = "0.1", features = ["log"] }
slight-common = { path = "../common" }
dyn-clone = "1"
async-trait = { workspace = true }

[dev-dependencies]
slight-kv = { path = "../kv" }
tokio = { version = "1", features = ["full"] }