[package]
name = "runtime"
version = "0.1.0"
edition = "2021"
authors = ["DeisLabs Engineering Team"]

[lib]
doctest = false
test = false

[dependencies]
wasmtime = "0.35"
wasmtime-wasi = "0.35"
wasi-common = "0.35"
wasi-cap-std-sync = "0.35"
anyhow = "1"
as-any = "0.3"
wit-bindgen-wasmtime = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "a79a4be33d76ddf62839ba71602c26a96610ef7c" }
crossbeam-channel = "0.5.5"
events-api = { path = "../events-api" }
tracing = { version = "0.1", features = ["log"] }
