[package]
name = "slight-runtime"
version = "0.1.0"
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }
wasi-common = { workspace = true }
wasi-cap-std-sync = { workspace = true }
anyhow = { workspace = true }
as-any = { workspace = true }
crossbeam-channel = "0.5"
slight-http-api = { workspace = true }
tracing = { workspace = true }
slight-common = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
slight-keyvalue = { workspace = true }
tokio = { workspace = true }