[package]
name = "runtime"
version = "0.1.0"
edition = "2021"
authors = ["DeisLabs Engineering Team"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "0.35"
wasmtime-wasi = "0.35"
wasi-common = "0.35"
wasi-cap-std-sync = "0.35"
wit-bindgen-wasmtime = { git = "https://github.com/bytecodealliance/wit-bindgen" }
anyhow = "1"
url = "2.2"
kv-filesystem = { path = "../kv-filesystem" }
kv-azure-blob = { path = "../kv-azure-blob" }
mq-filesystem = { path = "../mq-filesystem" }
capability = { path = "../capability" }
as-any = "0.3"
