specversion = "0.2"

[[capability]]
resource = "messaging.nats"
name = "my-messaging"
    [capability.configs]
    NATS_CREDS = "${azapp.NATS_CREDS_PATH}"
    # eventually, we'd like to support the ability to not pass in any creds, or connect via:
    #   - username/password
    #   - certificates
    # also, rn, we assume a connection to 'connect.ngs.global', but we'd like to support other endpoints