[package]
name = "slight-pubsub"
version = "0.1.0"
edition = "2021"
authors = ["DeisLabs Engineering Team"]

[lib]
test = false
doctest = false

[dependencies]
anyhow = "1"
wit-bindgen-wasmtime = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "a79a4be33d76ddf62839ba71602c26a96610ef7c" }
wit-error-rs = { git = "https://github.com/danbugs/wit-error-rs", rev = "05362f1a4a3a9dc6a1de39195e06d2d5d6491a5e" }
slight-common = { path = "../common" }
slight-events-api = { path = "../events-api" }
slight-runtime-configs = { path = "../runtime-configs" }
uuid = { version = "1.1", features = ["v4"] }
tracing = { version = "0.1", features = ["log"] }
crossbeam-channel = "0.5"
url = "2"
# pubsub.confluent_apache_kafka deps
rdkafka = { version = "0.28", features = ["cmake-build", "ssl"] }
# pubsub.mosquitto
names = { version = "0.14.0", default-features = false }

[target.'cfg(unix)'.dependencies]
mosquitto-client-wrapper = "0.3"

[target.'cfg(windows)'.dependencies]
mosquitto-client = { git = "https://github.com/jsloth/mosquitto-client", rev = "7913a98bfe6d35aaec9b541e7be4b817c42d91e0"}
