[package]
name = "slight-pubsub"
version = "0.1.0"
edition = "2021"
authors = ["DeisLabs Engineering Team"]

[lib]
test = false
doctest = false

[dependencies]
anyhow = "1"
wit-bindgen-wasmtime = { git = "https://github.com/bytecodealliance/wit-bindgen", tag = "v0.2.0", features = ["async"]}
wit-error-rs = { git = "https://github.com/danbugs/wit-error-rs", rev = "05362f1a4a3a9dc6a1de39195e06d2d5d6491a5e" }
slight-common = { path = "../common" }
slight-events-api = { path = "../events-api" }
slight-runtime-configs = { path = "../runtime-configs" }
uuid = { version = "1.1", features = ["v4"] }
tracing = { version = "0.1", features = ["log"] }
crossbeam-channel = "0.5"
url = "2"
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
# pubsub.confluent_apache_kafka deps
rdkafka = { version = "0.28", features = ["cmake-build", "ssl"] }
# pubsub.mosquitto
mosquitto-rs = { version = "0.4.0", features = ["default"] }
async-channel = "1.5"