specversion = "0.2"

[[capability]]
resource = "blobstore.azblob"
name = "slight-example-bucket"
    [capability.configs]
    AZURE_STORAGE_ACCOUNT = "${azapp.AZURE_STORAGE_ACCOUNT}"
    AZURE_STORAGE_KEY = "${azapp.AZURE_STORAGE_KEY}"