[package]
name = "proc_macro_utils"
version = "0.1.0"
edition = "2021"
authors = ["DeisLabs Engineering Team"]

[lib]
proc-macro = true
test = false
doctest = false

[dependencies]
syn = "1.0.96"
quote = "1.0.18"