[package]
name = "slight"
version = "0.1.0"
edition = "2021"
authors = ["DeisLabs Engineering Team"]

[[bin]]
name = "slight"
test = false

[lib]
name = "slight_lib"
path = "src/lib.rs"

[dependencies]
spiderlightning = { path = "../" }
slight-runtime = { path = "../crates/runtime" }
slight-kv = { path = "../crates/kv" }
slight-mq = { path = "../crates/mq" }
slight-lockd = { path = "../crates/lockd" }
slight-pubsub = { path = "../crates/pubsub" }
slight-runtime-configs = { path = "../crates/runtime-configs" }
slight-common = { path = "../crates/common" }
slight-events = { path = "../crates/events" }
slight-events-api = { path = "../crates/events-api" }
slight-http = { path = "../crates/http" }
anyhow = "1"
env_logger = "0.9"
log = { version = "0.4", default-features = false }
tokio = { version = "1", features = ["full"] }
wit-bindgen-wasmtime = { git = "https://github.com/bytecodealliance/wit-bindgen", tag = "v0.2.0"}
clap = { version = "3", features = ["derive"] }
toml = "0.5"
as-any = "0.3"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing = { version = "0.1", features = ["log"] }
reqwest = "0.11"

[dev-dependencies]
tempdir = "0.3"