specversion = "0.1"
secret_store = "envvars"

# [[secret_settings]]
# name = "AZURE_STORAGE_ACCOUNT"
# value = "8u__-nP7_qZivo3r3i2i37_9v"

# [[secret_settings]]
# name = "AZURE_STORAGE_KEY"
# value = "8uh6svq5qX-D53Dy7E2Q773KUOb0Xpi6u-l1tfu_jXOoyDar2PDYQs_j9VPG2c4jLqdx5zrB4iu6J7DK04Uab23P7Koz6YMrB_NZb1MQkguqA6XGxrVe2yQ"

[[capability]]
name = "azblobkv"

[[capability]]
name = "events"
