specversion = "0.1"

[[capability]]
resource = "kv.azblob"
name = "my-container"
    [capability.configs]
    AZURE_STORAGE_ACCOUNT = "${azapp.AZURE_STORAGE_ACCOUNT}"
    AZURE_STORAGE_KEY =  "${azapp.AZURE_STORAGE_KEY}"