[package]
name = "keyvalue-demo"
version = "0.1.0"
edition = "2021"
authors = ["DeisLabs Engineering Team"]

[[bin]]
name = "keyvalue-demo"
test = false

[dependencies]
wit-bindgen-rust = { git = "https://github.com/fermyon/wit-bindgen-backport" }
anyhow = "1"
wit-error-rs = { git = "https://github.com/danbugs/wit-error-rs", rev = "05362f1a4a3a9dc6a1de39195e06d2d5d6491a5e" }
serde_json = "1"

[workspace]
