specversion = "0.2"

[[capability]]
resource = "keyvalue.awsdynamodb"
name = "my-container"
    # This capability loads its' config from environment variables. It requires:
    #   - `AWS_ACCESS_KEY_ID`,
    #   - `AWS_SECRET_ACCESS_KEY`, and
    #   - `AWS_REGION`.

[[capability]]
resource = "keyvalue.awsdynamodb"
name = "my-container2"
    # This capability loads its' config from environment variables. It requires:
    #   - `AWS_ACCESS_KEY_ID`,
    #   - `AWS_SECRET_ACCESS_KEY`, and
    #   - `AWS_REGION`.
