// A key-value store interface.
use { payload } from types
use * from resources

enum error {
	// getting a key-value store resource descriptor failed.
    descriptor-error, 
	// getting the payload for a given key failed.
	io-error,
	// other errors.
	other-error,
}

// get a key-value store resource descriptor.
get-blob: function() -> expected<resource-descriptor, error>

// get the payload for a given key.
get: function(rd: resource-descriptor, key: string) -> expected<payload, error> 

// set the payload for a given key.
set: function(rd: resource-descriptor, key: string, value: payload) -> expected<unit, error>

// delete the payload for a given key.
delete: function(rd: resource-descriptor, key:string) -> expected<unit, error>
