// An App Configuration Interface
use { error, payload } from types

resource configs {
    // Obtain an app config store, identifiable through a resource descriptor
    static open: function() -> expected<configs, error>

    // Get an app configuration given a config store, and an identifiable key
    get: function(key: string) -> expected<payload, error>

    // Set an app configuration given a config store, an identifiable key, and its' value
    set: function(key: string, value: payload) -> expected<unit, error>
}