// An App Configuration Interface
use { error, payload } from types

resource configs {
    // Obtain an app config store, identifiable through a resource descriptor
    static open: func(name: string) -> expected<configs, error>

    // Get an app configuration given a config store, and an identifiable key
    get: func(key: string) -> expected<payload, error>

    // Set an app configuration given a config store, an identifiable key, and its' value
    set: func(key: string, value: payload) -> expected<unit, error>
}