/// a distruted locking interface
resource distributed-locking {
	/// open a distributed-locking object
	static open: func(name: string) -> expected<distributed-locking, distributed-locking-error>

	/// creates a lock with a name, returns the lock key
	lock: func(lock-name: list<u8>) -> expected<list<u8>, distributed-locking-error>

	/// creates a lock with a lease id, hence giving the lock a TTL
	lock-with-time-to-live: func(lock-name: list<u8>, time-to-live-in-secs: s64) -> expected<list<u8>, distributed-locking-error>

	/// unlock a lock given a lock key
	unlock: func(lock-key: list<u8>) -> expected<unit, distributed-locking-error>
}

// common distributed errors
variant distributed-locking-error {
	lock-acquire-error(string),
	lock-release-error(string),
	lock-timeout-error(string),
	connection-error(string),
	protocol-error(string),
	invalid-lock-id(string),
	unexpected-error(string)
}