use { observable } from resources
use { error } from types


resource events {
	static get: func() -> expected<events, error>
	listen: func(ob: observable) -> expected<events, error>
	exec: func(duration: u64) -> expected<unit, error>
}
