use { observable } from resources
use { error } from types


resource events {
	static get: function() -> expected<events, error>
	listen: function(ob: observable) -> expected<events, error>
	exec: function(duration: u64) -> expected<unit, error>
}
