variant gpio-error {
  configuration-error(string),
  pin-usage-error(string),
  hardware-error(string),
  unexpected-error(string),
}

enum logic-level {
  low,
  high,
}

resource input-pin {
  static get-named: func(name: string) -> expected<input-pin, gpio-error>

  read: func() -> logic-level
}

resource output-pin {
  static get-named: func(name: string) -> expected<output-pin, gpio-error>

  write: func(level: logic-level) -> unit
}
