// A key-value store interface.
use { error, payload } from types
use { observable } from resources

resource kv {
	// open a key-value store
	static open: function(name: string) -> expected<kv, error>

	// get the payload for a given key.
	get: function(key: string) -> expected<payload, error> 

	// set the payload for a given key.
	set: function(key: string, value: payload) -> expected<unit, error>

	// delete the payload for a given key.
	delete: function(key:string) -> expected<unit, error>

	// watch for changes to a key.
	watch: function(key: string) -> expected<observable, error>
}