// A Message Queue Interface
use { error, payload } from types
use * from resources

resource mq {
	// open a message queue
	static open: func(name: string) -> expected<mq, error>

	// send a message to the queue
	send: func(msg: payload) -> expected<unit, error> 

	// receive a message from the queue
	receive: func() -> expected<payload, error>
}