// A Pub/Sub Interface
use { message, error, payload } from types
use * from resources

resource pubsub {
	// open a pub/sub object
	static open: function() -> expected<pubsub, error>

	// pub a message
	send-message-to-topic: function(msg-key: payload, msg-value: payload, topic: string) -> expected<unit, error> 

	// sub to a topic
	subscribe-to-topic: function(topic: list<string>) -> expected<unit, error>

	// print messages under subbed topic
	poll-for-message: function(timeout-in-secs: u64) -> expected<message, error>
}