// A Pub/Sub Interface
use { error, payload } from types
use * from resources

resource pub {
	// open a pub object
	static open: func() -> expected<pub, error>

	// pub a message
	publish: func(message: payload, topic: string) -> expected<unit, error> 
}

resource sub {
	// open a sub object
	static open: func() -> expected<sub, error>
	
	// sub to a topic
	subscribe: func(topic: string) -> expected<unit, error>

	// read messages under subbed topic
	receive: func() -> expected<payload, error>
}