// A Pub/Sub Interface
use { error, payload } from types
use * from resources

// get the resource-descriptor for pub/sub
get-pubsub: function() -> expected<resource-descriptor, error>

// pub a message
send-message-to-topic: function(rd: resource-descriptor, msg-key: payload, msg-value: payload, topic: string) -> expected<unit, error> 

// sub to a topic
subscribe-to-topic: function(rd: resource-descriptor, topic: list<string>) -> expected<unit, error>

// print messages under subbed topic
print-message-stream: function(rd: resource-descriptor) -> expected<unit, error>