variant error {
	error-with-description(string),
}
type payload = list<u8>
type map = list<tuple<string, string>>

record message {
	key: option<payload>,
	value: option<payload>
}

record event {
	specversion: string,
	event-type: string,
	source: string,
	id: string,
	data: option<string>
} 
