specversion = "0.2"

[[capability]]
resource = "keyvalue.azblob"
name = "my-container"
    [capability.configs]
    AZURE_STORAGE_ACCOUNT = "${azapp.AZURE_STORAGE_ACCOUNT}"
    AZURE_STORAGE_KEY =  "${azapp.AZURE_STORAGE_KEY}"

[[capability]]
resource = "messaging.azsbus"
name = "wasi-cloud-queue"
    [capability.configs]
    AZURE_SERVICE_BUS_NAMESPACE = "${azapp.AZURE_SERVICE_BUS_NAMESPACE}"
    AZURE_POLICY_NAME = "${azapp.AZURE_POLICY_NAME}"
    AZURE_POLICY_KEY = "${azapp.AZURE_POLICY_KEY}"