[package]
name = "pubsub-consumer-demo"
version = "0.1.0"
edition = "2021"
authors = ["DeisLabs Engineering Team"]

[[bin]]
name = "pubsub-consumer-demo"
test = false

[dependencies]
wit-bindgen-rust = { git = "https://github.com/bytecodealliance/wit-bindgen", rev= "a79a4be33d76ddf62839ba71602c26a96610ef7c" }
anyhow = "1"
wit-error-rs = { git = "https://github.com/danbugs/wit-error-rs", rev = "05362f1a4a3a9dc6a1de39195e06d2d5d6491a5e" }