specversion = "0.1"

[[capability]]
resource = "http"
name = "my-rest-api"
    # This capability does not require any configs

[[capability]]
resource = "kv.awsdynamodb"
name = "my-container"
    # This capability loads its' config from environment variables. It requires:
    #   - `AWS_ACCESS_KEY_ID`,
    #   - `AWS_SECRET_ACCESS_KEY`, and
    #   - `AWS_REGION`.

