specversion = "0.2"

[[capability]]
resource = "keyvalue.filesystem"
name = "my-container"
    # This capability does not require any configs

[[capability]]
resource = "mq.filesystem"
name = "wasi-cloud-queue"
    # This capability does not require any configs