specversion = "0.1"

[[capability]]
resource = "kv.filesystem"
name = "my-container"
    # This capability does not require any configs

[[capability]]
resource = "mq.filesystem"
name = "wasi-cloud-queue"
    # This capability does not require any configs