specversion = "0.2"

[[secret_settings]]
name = "THIS_IS_ANOTHER_TEST_CONFIG_1061408"
value = "BlRpAgMpCY2OGkWUaAg"

[[secret_settings]]
name = "THIS_IS_ANOTHER_TEST_CONFIG_1061296"
value = "b40pEta78QMX1_vZdjQ"

[[secret_settings]]
name = "THIS_IS_ANOTHER_TEST_CONFIG_1061248"
value = "M8yXDCt8wbMe3Oi10fQ"

[[secret_settings]]
name = "THIS_IS_ANOTHER_TEST_CONFIG_1061312"
value = "b40pEta78QMX1_vZdjQ"

[[secret_settings]]
name = "THIS_IS_ANOTHER_TEST_CONFIG_1061312"
value = "4ODbvnPBytYMp0tOZZw"

[[secret_settings]]
name = "THIS_IS_ANOTHER_TEST_CONFIG_1061136"
value = "ViTjHeyPFRXBA1ZAAMg"

[[capability]]
resource = "configs.usersecrets"
name = "my-secret-store"
