specversion = "0.1"

[[secret_settings]]
name = "THIS_IS_ANOTHER_TEST_CONFIG_1061408"
value = "m7N0Muoz0ICs7Owemrg"

[[secret_settings]]
name = "THIS_IS_ANOTHER_TEST_CONFIG_1061296"
value = "g88GVRuP1o2aqE6L1Mg"

[[secret_settings]]
name = "THIS_IS_ANOTHER_TEST_CONFIG_1061248"
value = "g88GVRuP1o2aqE6L1Mg"

[[secret_settings]]
name = "THIS_IS_ANOTHER_TEST_CONFIG_1061280"
value = "4ODbvnPBytYMp0tOZZw"

[[capability]]
name = "configs.usersecrets"
